Import('env')

env['LIBS'] = [
    'asynchttp',
]

env['CPPPATH'] = [
    '../components/asynchttp/include',
]

env['LIBPATH'] = [
    '../components/asynchttp/lib',
]

env.ParseConfig(env['CONFIG_PARSER'])

env.Substfile('fstracecheck.in',
              '#fstracecheck.in',
              SUBST_DICT={
                  '@ARCHBUILDDIR@': env['ARCHBUILDDIR'],
                  '@FSTRACECHECK2@': env['FSTRACECHECK2'],
              }
)
env.Command('fstracecheck',
            'fstracecheck.in',
            [
                Copy('$TARGET', '$SOURCE'),
                Chmod('$TARGET', 0o755),
            ]
)

env.Program('webget',
            [ 'webget.c' ])

env.Program('webclient',
            [ 'webclient.c' ])

env.Program('icapscan',
            [ 'icapscan.c' ])
